swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:    
  /login/:
    post:
      tags:
      - login
      description: Logs user into the system
      operationId: LoginController.Login
      parameters:
      - in: body
        name: body
        description: email and password
        required: true
        schema:
          $ref: '#/definitions/models.LoginInput'
      responses:
        "200":
          description: '{string} token and {string} refreshtoken'
        "403":
          description: Wrong Email or Password
        "500":
          description: error message
          definitions:
            helper.LoginInput:
              title: LoginInput
              type: object
              properties:
                device_id:
                  type: string
                email:
                  type: string
                password:
                  type: string

tags:
- name: login
  description: |
     LoginController operations for Login
