version: "3"
services:
  ms-customer:
    image: golang:1.14
    command: ["go", "run", "main.go"]
    working_dir: /demo
    depends_on:
      - postgres
    environment:
        HTTP_PORT: 80
        GOPATH: /gopath  
    ports:
      - 8089:80

  postgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: thanh@gmail.com
        PGADMIN_DEFAULT_PASSWORD: 123456
        PGADMIN_LISTEN_PORT: 8001
    ports:
      - "8001:8001"
    links:
      - "postgres:sofmie.com"